import Image from 'next/image';
import { ArrowUpRight, Download, ExternalLink, GitFork, Mail } from 'lucide-react';

type Project = { title: string; year: string; description: string; tags: string[]; repo: string; demo?: string };
const scientificProjects: Project[] = [
  { title: 'KOL Radar', year: '2026', description: 'A transparent research workspace for comparing Chilean specialists, institutions, and public scientific signals.', tags: ['Medical Affairs', 'Evidence'], repo: 'https://github.com/FranciscoKirhman/kol-radar', demo: 'https://franciscokirhman.github.io/kol-radar/web/index.html' },
  { title: 'BiopREL', year: '2023', description: 'GelMA hydrogel analysis and Young’s modulus visualization across formulations.', tags: ['Python', 'Tableau'], repo: 'https://github.com/FranciscoKirhman/BiopREL', demo: 'https://public.tableau.com/app/profile/francisco.kirhman.osorio/vizzes' },
  { title: 'PlantFinder', year: '2024', description: 'A Chilean plant species query tool for species, distribution, and type.', tags: ['Node.js', 'Oracle'], repo: 'https://github.com/FranciscoKirhman/PlantFinder' },
  { title: 'NutriCal', year: '2024', description: 'A macro and micronutrient calculator for dietary guidelines and portions.', tags: ['Node.js', 'Oracle'], repo: 'https://github.com/FranciscoKirhman/NutriCal' },
];
const otherProjects: Project[] = [
  { title: 'Job Tracker', year: '2026', description: 'A self contained application tracker with structured data and automation utilities.', tags: ['HTML / JS', 'Automation'], repo: 'https://github.com/FranciscoKirhman/job-tracker' },
  { title: 'JobFinder', year: '2026', description: 'A recurring web monitoring tool for new opportunities.', tags: ['Automation', 'Monitoring'], repo: 'https://github.com/FranciscoKirhman/JobFinder' },
  { title: 'Training Dashboard', year: '2026', description: 'An interactive dashboard generated from structured profiles, routines, and progress history.', tags: ['Dashboard', 'Python'], repo: 'https://github.com/FranciscoKirhman/entrenamiento-dashboard', demo: 'https://franciscokirhman.github.io/entrenamiento-dashboard/' },
  { title: 'ChiliNews', year: '2025', description: 'A web based news experience focused on Chile.', tags: ['HTML', 'Web'], repo: 'https://github.com/FranciscoKirhman/ChiliNews', demo: 'https://franciscokirhman.github.io/ChiliNews/' },
];
const experience = [
  { number: '01', area: 'Medical education', title: 'Professional Education Specialist', place: 'Johnson & Johnson MedTech', date: '2025 to 2026', copy: 'Coordinated 10 national medical education programs across orthopaedic specialties, engaging approximately 260 healthcare professionals under HCC and HCBI compliance frameworks.' },
  { number: '02', area: 'Clinical research', title: 'Clinical Research Intern', place: 'Clínica Indisa', date: '2024 to 2025', copy: 'Reviewed clinical research protocols against GCP and regulatory requirements during a clinical research internship.' },
  { number: '03', area: 'Scientific research', title: 'Cancer genomics and biomaterials', place: 'UOH | Universidad de los Andes | PUC Chile', date: '', copy: 'Research across genomic bioinformatics, biomaterials, microbiology, and reproducible analysis, with two peer reviewed publications and one bioRxiv preprint.' },
];

function ProjectRow({ project }: { project: Project }) {
  return <article className="project-row"><p className="project-year">{project.year}</p><div className="project-copy"><h3>{project.title}</h3><p>{project.description}</p><ul aria-label={`${project.title} categories`}>{project.tags.map(tag => <li key={tag}>{tag}</li>)}</ul></div><div className="project-links"><a href={project.repo} target="_blank" rel="noreferrer" aria-label={`View ${project.title} source code`}>Source <GitFork aria-hidden="true" /></a>{project.demo && <a className="accent-link" href={project.demo} target="_blank" rel="noreferrer" aria-label={`View ${project.title}`}>View <ExternalLink aria-hidden="true" /></a>}</div></article>;
}

export default function Home() {
  return <main id="top"><a className="skip-link" href="#main-content">Skip to content</a>
    <header className="site-header shell"><a className="brand" href="#top"><span aria-hidden="true">FK</span><strong>Francisco Kirhman</strong></a><nav aria-label="Primary"><a href="#profile">Profile</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#connect">Contact</a></nav><a className="linkedin-link" href="https://www.linkedin.com/in/franciscokirhman/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight aria-hidden="true" /></a></header>
    <div id="main-content">
      <section className="hero shell" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span /> Medical Affairs and Scientific Portfolio</p><h1 id="hero-title">Scientific depth.<br /><em>Human connection.</em></h1><p className="hero-lede">Molecular Biotechnology Engineer bringing together cancer genomics research, clinical research training, and medical education experience to build toward Medical Science Liaison and Medical Affairs work.</p><div className="actions"><a className="button primary" href="/Francisco_Kirhman_MSL_CV.pdf" download><Download aria-hidden="true" /> Download MSL CV</a><a className="button secondary" href="mailto:francisco.osorio@ug.uchile.cl"><Mail aria-hidden="true" /> Email Francisco</a></div><dl className="hero-metrics"><div><dt>10</dt><dd>National medical education programs</dd></div><div><dt>260</dt><dd>Healthcare professionals engaged</dd></div><div><dt>2</dt><dd>Peer reviewed publications</dd></div></dl></div><figure className="portrait"><div className="portrait-frame"><Image src="/francisco-kirhman-profile.png" alt="Francisco Kirhman Osorio" fill priority sizes="(max-width: 800px) 90vw, 38vw" /></div><figcaption><span>Francisco Kirhman Osorio</span><span>Santiago, Chile</span></figcaption></figure></section>
      <section id="profile" className="profile-band"><div className="shell profile-grid"><p className="section-label">Profile</p><div><h2>Evidence led science, communicated with purpose.</h2><p>Molecular Biotechnology Engineer with research in cancer genomics, biomaterials, and microbiology; dual GCP certification; CITI Human Subjects Research training; a PUC Chile Diploma in Clinical Study Management; and HCP education coordination in a multinational MedTech setting.</p></div><aside><p>Areas of focus</p><ul><li>Medical education</li><li>Scientific communication</li><li>Clinical research</li><li>Evidence tools</li></ul></aside></div></section>
      <section id="experience" className="section shell" aria-labelledby="experience-title"><div className="section-intro"><p className="section-label">Relevant foundation</p><h2 id="experience-title">A path into Medical Affairs</h2></div><div className="experience-list">{experience.map(item => <article key={item.number}><p className="experience-number">{item.number}</p><div><p className="experience-area">{item.area}</p><h3>{item.title}</h3><p className="experience-meta">{item.place}{item.date && ` | ${item.date}`}</p></div><p className="experience-copy">{item.copy}</p></article>)}</div></section>
      <section className="feature-section"><div className="shell"><div className="section-intro split"><div><p className="section-label">Selected evidence</p><h2>Science translated into useful tools.</h2></div><p>Projects designed to make complex evidence easier to inspect, compare, and communicate.</p></div><div className="feature-grid"><article><p className="feature-kicker">01 | Scientific intelligence</p><h3>KOL Radar</h3><p>A transparent research workspace for comparing Chilean specialists, institutions, and public scientific signals. It supports research prioritization, not automatic KOL designation or outreach decisions.</p><a href="https://franciscokirhman.github.io/kol-radar/web/index.html" target="_blank" rel="noreferrer">Explore KOL Radar <ArrowUpRight aria-hidden="true" /></a></article><article><p className="feature-kicker">02 | Research visualization</p><h3>BiopREL</h3><p>Data analysis and visualization for GelMA hydrogel research, translating compressive data comparisons into inspectable dashboards and figures.</p><a href="https://public.tableau.com/app/profile/francisco.kirhman.osorio/vizzes" target="_blank" rel="noreferrer">View the dashboard <ArrowUpRight aria-hidden="true" /></a></article></div></div></section>
      <section id="projects" className="section shell" aria-labelledby="projects-title"><div className="section-intro"><p className="section-label">Project archive</p><h2 id="projects-title">Scientific and technical work</h2></div><div className="projects-table">{scientificProjects.map(p => <ProjectRow key={p.title} project={p} />)}</div><details className="other-projects"><summary>View personal and web projects <span aria-hidden="true">+</span></summary><div className="projects-table">{otherProjects.map(p => <ProjectRow key={p.title} project={p} />)}</div></details></section>
    </div>
    <footer id="connect"><div className="shell footer-grid"><div><p className="section-label">Let’s connect</p><h2>Interested in science that moves conversations forward?</h2></div><div className="footer-contact"><a href="mailto:francisco.osorio@ug.uchile.cl">francisco.osorio@ug.uchile.cl <ArrowUpRight aria-hidden="true" /></a><div><a href="/Francisco_Kirhman_MSL_CV.pdf" download>MSL CV</a><a href="https://www.linkedin.com/in/franciscokirhman/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/FranciscoKirhman" target="_blank" rel="noreferrer">GitHub</a><a href="https://www.kaggle.com/franciscokirhman" target="_blank" rel="noreferrer">Kaggle</a></div></div></div><div className="shell footer-base"><p>Francisco Kirhman Osorio | Santiago, Chile</p><p>Updated September 2026</p></div></footer>
  </main>;
}
